# This file configures the deployment settings for Netlify

# This file configures the deployment settings for Netlify

[build]
  # Use the special build command that ignores lint errors
  command = "npm run build:netlify"
  
  # The directory to publish, relative to the base directory
  publish = ".next"
  
  # The base directory where the frontend code is located
  base = "frontend-next"

# This is the essential plugin for running Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
