# This file configures the deployment settings for Netlify

[build]
  # The command to build the site
  command = "npm run build"
  
  # The directory to publish, which contains the built site
  publish = "frontend-next/.next"
  
  # The base directory, where the frontend code is located
  base = "frontend-next"
