# This file configures the deployment settings for Netlify

# This file configures the deployment settings for Netlify

[build]
  # The command to build the site
  command = "npm run build"
  
  # The directory to publish
  publish = ".next"

# This is the essential plugin for running Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
